name: Clang

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -yq libboost-all-dev clang-12 libace-dev
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-12 100 
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-12 100
    - name: Setup
      run: |
        mkdir bin
        cd bin
        cmake ../ -DTOOLS=1 -DELUNA=0 -DCMAKE_INSTALL_PREFIX=check_install
        cd ..
    - name: Build
      run: |
        cd bin
        make -j 4 -k && make install
    #- name: Check executables
    #  run: |
    #    cd bin/check_install/bin
    #    ./authserver --version
    #    ./worldserver --version
